version: '3.4'

services:
  api:
    build: .
    depends_on:
      - postgres
    volumes:
      - logs:/app/logs/
    ports:
      - "127.0.0.1:27181:3001"

  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "27190:5432"
    restart: always

volumes:
  logs:
